
server:
  port: 8085
  servlet:
    context-path: /user-course-connector-app

spring:
  application:
    name: user-course-connector-app
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/CONNECTOR_DB
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
