server:
  port: 9000

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: courses
          uri: http://localhost:8083
          predicates:
            - Path=/course-app/**
        - id: users
          uri: http://localhost:8084
          predicates:
            - Path=/user-app/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka