version: '3.9'

services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitUser'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net

  db:
    image: postgres
    restart: always

    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: USER_DB

    ports:
      - '5437:5432'
volumes:
  db:

networks:
  rabbitmq_go_net:
    driver: bridge